### ISSUE TITLE
Array of hosts for user access in secure section of parameters.yml

### ISSUE THREAD

**Issue by muxx** [intaro/pinboard#75]
Add ability to define array of hosts for user access settings. Example for `testuser3`:

``` yml
secure:
    enable: false
    users:
        testuser1:
            password: my_password1
        testuser2:
            password: my_password2
            hosts: 'example\.com$'
        testuser3:
            password: my_password3
            hosts:
               - 'example\.com$'
               - 'some\-domain\.net$'
```
