### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by kostyrev** [intaro/pinboard#89]
I experiencing the same issue https://github.com/intaro/pinboard/issues/85
I've installed it like this:
$ git clone git://github.com/intaro/pinboard.git
$ cd ./pinboard
$ git checkout v1.3

I've tried to use 
cache: array
but it didn't help.
When I start tcpdump on port specified in my.cnf with pinba_port directive, I can see traffic flowing.
When I turn on general_log in mysql I can see no inserts or whatever. Just selects provided by the console aggregate in cron.

```
cat /var/projects/projects/pinboard/config/parameters.yml
db:
    host: localhost
    port: 3306
    name: pinba
    user: pinba
    pass: thisisnotmypassword

logging:
    long_request_time:
        global: 1.0
    heavy_request:
        global: 30000
    heavy_cpu_request:
        global: 1

locale:  en

cache: array

records_lifetime: P2M
aggregation_period: PT5M

pagination:
    row_per_page: 50

secure:
    enable: false
```
